name: Release

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.0"

      - name: Binaries Release
        uses: goreleaser/goreleaser-action@v4.4.0
        with:
          version: ~> 1.16.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
